### ISSUE TITLE
Application initialization issues

### ISSUE THREAD

**Issue by BrianVB** [META1CoinTrust/meta1-dex#1]
I am not certain if this is a bug or intended in this stage of development but when following the instructions to run the dev server after visiting http://localhost:8080/home/ in my browser (both Firefox and Chrome) it redirects / cycles through a loading screen several times and stops on a page that says "Application initialization issues"

**To Reproduce**
Follow README to run dev server. Visit http://localhost:8080 in a browser.

**Expected behavior**
Not certain

**Screenshots**
![Screenshot from 2020-05-14 21-16-51](https://user-images.githubusercontent.com/3021082/82001111-58268880-9628-11ea-9dc8-7240da0e8aab.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.3 LTS
 - Browser Chrome and Firefox

**Comment by meta1admin** [comment]
Hello,

there is no API server running on that address. Once we release meta1-core repository you will be able to build local API and connect.

Please, keep in mind that we are running private testnet during development and code is here for review, not for production.

Best regards,

Meta1 Team

**Comment by BVBAccelm** [comment]
Okay, so this is normal for this stage of development - thank you for explaining.
